pub mod auth;
pub mod contacts;
pub mod dashboard;
pub mod documents;
pub mod email;
pub mod engagements;
pub mod invoices;
pub mod offers;
pub mod receipts;
pub mod reports;

pub use auth::{LoginPage, SetupPage};
pub use contacts::ContactsPage;
pub use dashboard::DashboardPage;
pub use documents::DocumentsPage;
pub use email::EmailPage;
pub use engagements::EngagementsPage;
pub use invoices::InvoicesPage;
pub use offers::OffersPage;
pub use receipts::ReceiptsPage;
pub use reports::ReportsPage;
